### ISSUE TITLE
Event stream quits immediately with Chromium

### ISSUE THREAD

**Issue by muni-corn** [Mange/mpris-rs#49]
Library version 1.1.2.

`playerctl` seems to follow events fine, but this library seems to crash with Chromium.

Running the `events.rs` example in the `examples/` folder produces this output:

```
~ $ env RUST_BACKTRACE=full cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
     Running `target/debug/sandbox`
Showing event stream for player Chromium...
(Exit with Ctrl-C)

thread 'main' panicked at 'Could not start event stream: DBusError { message: "error occurred in Get" }', src/main.rs:15:18
stack backtrace:
   0:     0x560f2817c5e4 - backtrace::backtrace::libunwind::trace::h6bd2a408dd6baea6
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:     0x560f2817c5e4 - backtrace::backtrace::trace_unsynchronized::h66fd2c866e4a8dab
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:     0x560f2817c5e4 - std::sys_common::backtrace::_print_fmt::h1a21ffb8376fb394
                               at src/libstd/sys_common/backtrace.rs:78
   3:     0x560f2817c5e4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf1fa8bbccd6e3337
                               at src/libstd/sys_common/backtrace.rs:59
   4:     0x560f2819a59c - core::fmt::write::h67c86c44f76f30dc
                               at src/libcore/fmt/mod.rs:1052
   5:     0x560f2817a817 - std::io::Write::write_fmt::h6e613689dc5020a6
                               at src/libstd/io/mod.rs:1428
   6:     0x560f2817eae5 - std::sys_common::backtrace::_print::hff16a4af54ff7d0c
                               at src/libstd/sys_common/backtrace.rs:62
   7:     0x560f2817eae5 - std::sys_common::backtrace::print::hc01517138f08d196
                               at src/libstd/sys_common/backtrace.rs:49
   8:     0x560f2817eae5 - std::panicking::default_hook::{{closure}}::h5f3b0f000ef82083
                               at src/libstd/panicking.rs:204
   9:     0x560f2817e826 - std::panicking::default_hook::h2a95ea05805d33c5
                               at src/libstd/panicking.rs:224
  10:     0x560f2817f142 - std::panicking::rust_panic_with_hook::h6311186fea61d761
                               at src/libstd/panicking.rs:470
  11:     0x560f2817ed2b - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:     0x560f28198b81 - core::panicking::panic_fmt::hdb2db7e65c163336
                               at src/libcore/panicking.rs:85
  13:     0x560f281989a3 - core::option::expect_none_failed::h7f6e8594d8fdcb5a
                               at src/libcore/option.rs:1211
  14:     0x560f28082b12 - core::result::Result<T,E>::expect::hf67b2e4a4cb40548
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libcore/result.rs:961
  15:     0x560f280819a4 - sandbox::main::h30a509f47809930f
                               at src/main.rs:15
  16:     0x560f28082d2b - std::rt::lang_start::{{closure}}::hd368c891acfa6a74
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/rt.rs:67
  17:     0x560f2817ec03 - std::rt::lang_start_internal::{{closure}}::hb4275c2c10281151
                               at src/libstd/rt.rs:52
  18:     0x560f2817ec03 - std::panicking::try::do_call::h72174d65d664912a
                               at src/libstd/panicking.rs:303
  19:     0x560f28180d97 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  20:     0x560f2817f6b9 - std::panicking::try::h9f5ccf2da82af734
                               at src/libstd/panicking.rs:281
  21:     0x560f2817f6b9 - std::panic::catch_unwind::h0027f7376f6d9883
                               at src/libstd/panic.rs:394
  22:     0x560f2817f6b9 - std::rt::lang_start_internal::h83680025af8c9f98
                               at src/libstd/rt.rs:51
  23:     0x560f28082d07 - std::rt::lang_start::h90f796f61ce9247e
                               at /rustc/5e7af4669f80e5f682141f050193ab679afdb4b1/src/libstd/rt.rs:67
  24:     0x560f280823ca - main
  25:     0x7f57d6682153 - __libc_start_main
  26:     0x560f2808115e - _start
  27:                0x0 - <unknown>
```

**Comment by Mange** [comment]
That's weird. I can't really tell where this happens from the backtrace; maybe the issue is inside the `dbus` crate?

Do the other examples work with Chromium for you?

**Comment by Mange** [comment]
Maybe this could be related to #50?

**Comment by djmaze** [comment]
Same problem here. Seems not to be fixed yet.

**Comment by Mange** [comment]
Have you tested the latest `master` commit or just the latest release, @djmaze?

**Comment by djmaze** [comment]
Right, only tested the release so far. Will have a try!

**Comment by djmaze** [comment]
Interesting. With master as opposed to 1.1.2, it seems to work!
